CREATE TABLE T_ORDER (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    ORDER_NUMBER VARCHAR(255) DEFAULT NULL,
    SKU_CODE VARCHAR(255),
    PRICE DECIMAL(19, 2),
    QUANTITY INTEGER,
    PRIMARY KEY(ID)
);
