spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
application:
  inventory:
    service:
      url: http://localhost:8082
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

#Resilience4J Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

  #Resilience4J Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
