version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory_mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
